# Generated by Django 5.0.14 on 2025-05-27 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyTracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('head_circumference', models.FloatField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='userAPI.baby')),
            ],
            options={
                'db_table': 'baby_tracking',
            },
        ),
    ]
