# Generated by Django 5.2 on 2025-05-29 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('value', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='userAPI.baby')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='userAPI.parent')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
