# Generated by Django 5.0.14 on 2025-06-01 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0003_remove_appointment_baby_parent_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biberon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('source', models.CharField(choices=[('sein', 'Sein'), ('lait_artificiel', 'Lait artificiel')], max_length=20)),
                ('remarque', models.CharField(blank=True, max_length=255, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biberons', to='userAPI.baby')),
            ],
            options={
                'db_table': 'biberon',
            },
        ),
    ]