# Generated by Django 5.2 on 2025-05-31 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0003_remove_appointment_baby_parent_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mixte', 'Mixte'), ('urine', 'Urine'), ('souillee', 'Souillée')], max_length=20)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('cause', models.CharField(blank=True, choices=[('Normale', 'Normale'), ('Diarrhée', 'Diarrhée'), ('Molle', 'Molle'), ('Liquide', 'Liquide'), ('Constipation', 'Constipation'), ('Autre', 'Autre')], max_length=30)),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couches', to='userAPI.baby')),
            ],
            options={
                'db_table': 'couche',
            },
        ),
        migrations.CreateModel(
            name='Tetee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('temps_passe', models.PositiveIntegerField()),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tetees', to='userAPI.baby')),
            ],
            options={
                'db_table': 'tetee',
            },
        ),
    ]
