# Generated by Django 5.0.14 on 2025-06-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0004_biberon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solides',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('fruit', 'Fruit'), ('legumes', 'Légumes'), ('cereales', 'Céréales'), ('viandes', 'Viandes'), ('proteines', 'Protéines')], max_length=20)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('quantite', models.IntegerField()),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solides', to='userAPI.baby')),
            ],
            options={
                'db_table': 'solides',
            },
        ),
    ]
