# Generated by Django 5.0.14 on 2025-06-04 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0005_category_advice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('temperature', models.FloatField()),
                ('remarque', models.CharField(blank=True, max_length=255, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='userAPI.baby')),
            ],
            options={
                'db_table': 'temperature',
            },
        ),
    ]
