# Generated by Django 5.0.14 on 2025-06-02 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0005_solides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sommeil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('remarque', models.CharField(blank=True, max_length=255, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sommeils', to='userAPI.baby')),
            ],
            options={
                'db_table': 'sommeils',
            },
        )
    ]
