# Generated by Django 5.0.14 on 2025-06-03 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0006_sommeil'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='expo_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BabyTracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('head_circumference', models.FloatField()),
                ('date_recorded', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='userAPI.baby')),
            ],
            options={
                'db_table': 'baby_tracking',
            },
        ),
        migrations.CreateModel(
            name='Couche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mixte', 'Mixte'), ('urine', 'Urine'), ('souillee', 'Souillée')], max_length=20)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('cause', models.CharField(blank=True, choices=[('Normale', 'Normale'), ('Diarrhée', 'Diarrhée'), ('Molle', 'Molle'), ('Liquide', 'Liquide'), ('Constipation', 'Constipation'), ('Autre', 'Autre')], max_length=30)),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couches', to='userAPI.baby')),
            ],
            options={
                'db_table': 'couche',
            },
        ),
        migrations.CreateModel(
            name='Tetee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('temps_passe', models.IntegerField()),
                ('remarque', models.CharField(blank=True, max_length=255, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tetees', to='userAPI.baby')),
            ],
            options={
                'db_table': 'tetee',
            },
        ),
    ]
