# Generated by Django 5.0.14 on 2025-06-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0006_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('heure', models.TimeField()),
                ('dosage', models.CharField(max_length=255)),
                ('remarque', models.CharField(blank=True, max_length=255, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='userAPI.baby')),
            ],
            options={
                'db_table': 'medicament',
            },
        ),
    ]
