# Generated by Django 4.2.22 on 2025-06-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0007_medicament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('symptomes', models.JSONField()),
                ('remarque', models.TextField(blank=True, null=True)),
                ('predicted_disease', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('precautions', models.JSONField(blank=True, null=True)),
                ('top_5_diseases', models.JSONField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_entries', to='userAPI.baby')),
            ],
        ),
    ]
