# Generated by Django 4.2.22 on 2025-06-05 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0007_medicament'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='CryDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cry_detections', to='userAPI.baby')),
            ],
            options={
                'db_table': 'cryDetection',
            },
        ),
    ]
