# Generated by Django 4.2.22 on 2025-06-05 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0008_symptome'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='symptome',
            table='symptome',
        ),
    ]
