# Generated by Django 4.2.22 on 2025-06-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0009_update_symptome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptome',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
