from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from .views import add_medicament, add_temperature, add_tetee, delete_medicament, delete_temperature, delete_tetee, get_medicaments_by_baby, get_temperatures_by_baby, get_tetees_by_baby, login_parent,register_parent, get_parent_by_id, add_baby, get_baby_by_id, get_babies_by_parent_id, update_baby, get_appointments_by_parent_id, add_appointment, update_appointment, delete_appointment, update_medicament, update_temperature, update_tetee, detect_cry
from .views import TestView, add_couche, update_couche, delete_couche, get_couches_by_baby, get_advice,get_advice_by_category, get_children_schedules
from .views import add_biberon, add_solide, add_sommeil, add_tetee, delete_biberon, delete_solide, delete_sommeil, delete_tetee, get_biberons_by_baby, get_solides_by_baby, get_sommeils_by_baby, get_tetees_by_baby, login_parent,register_parent, get_parent_by_id, add_baby, get_baby_by_id, get_babies_by_parent_id, update_baby, get_appointments_by_parent_id, add_appointment, update_appointment, delete_appointment, update_biberon, update_solide, update_sommeil, update_tetee 
from .views import TestView, add_couche, update_couche, delete_couche, get_couches_by_baby,get_tracking_by_baby_id,add_tracking,save_expo_token, delete_baby


urlpatterns = [
    path('test', TestView.as_view()),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('user/register/', register_parent, name="register_user"),
    path('user/login_parent/',login_parent,name="login_user"),
    path('parent/<int:parent_id>/', get_parent_by_id, name='get_parent_by_id'),
    path('user/add_baby/', add_baby, name='add_baby'),
    path('user/get_baby_by_id/<int:baby_id>/', get_baby_by_id, name='get_baby_by_id'),
    path('user/get_babies_by_parent_id/<int:parent_id>/', get_babies_by_parent_id, name='get_babies_by_id'),
    path('user/update_baby/<int:baby_id>/', update_baby, name='update_baby'),
    path('user/add_tracking/', add_tracking, name='add_tracking'),
    path('user/get_appointments_by_parent_id/<int:parent_id>/', get_appointments_by_parent_id, name='get_appointments_by_parent_id'),
    path('user/add_appointment/', add_appointment, name='add_appointment'),
    path('user/update_appointment/<int:appointment_id>/', update_appointment, name='update_appointment'),
    path('user/delete_appointment/<int:appointment_id>/', delete_appointment, name='delete_appointment'),
    path('couches/', add_couche, name='add_couche'), 
    path('couches/<int:couche_id>/', update_couche, name='update_couche'), 
    path('couches/<int:couche_id>/delete/', delete_couche, name='delete_couche'), 
    path('couches/baby/<int:baby_id>/', get_couches_by_baby, name='get_couches_by_baby'), 
    path('tetees/', add_tetee, name='add_tetee'),
    path('tetees/baby/<int:baby_id>/', get_tetees_by_baby, name='get_tetees_by_baby'),
    path('tetees/<int:tetee_id>/', update_tetee, name='update_tetee'), 
    path('tetees/<int:tetee_id>/delete/', delete_tetee, name='delete_tetee'),
    path('tetees/baby/<int:baby_id>/', get_tetees_by_baby, name='get_tetees_by_baby'),
    path('advice/', get_advice, name='get_advice'),
    path('advice/category/<str:category>/', get_advice_by_category, name='get_advice_by_category'),
    path('user/get_children_schedules/<int:parent_id>/', get_children_schedules, name='get_children_schedules'),
    
    path('user/get_last_traking/<int:baby_id>/',get_tracking_by_baby_id, name='get_last_traking'),
    path('biberons/', add_biberon, name='add_biberon'),
    path('biberons/baby/<int:baby_id>/', get_biberons_by_baby, name='get_biberons_by_baby'),
    path('biberons/<int:biberon_id>/', update_biberon, name='update_biberon'),
    path('biberons/<int:biberon_id>/delete/', delete_biberon, name='delete_biberon'),
    path('solides/', add_solide, name='add_solide'),
    path('solides/baby/<int:baby_id>/', get_solides_by_baby, name='get_solides_by_baby'),
    path('solides/<int:solide_id>/', update_solide, name='update_solide'),
    path('solides/<int:solide_id>/delete/', delete_solide, name='delete_solide'),
    path('sommeils/', add_sommeil, name='add_sommeil'),
    path('sommeils/baby/<int:baby_id>/', get_sommeils_by_baby, name='get_sommeils_by_baby'),
    path('sommeils/<int:sommeil_id>/', update_sommeil, name='update_sommeil'),
    path('sommeils/<int:sommeil_id>/delete/', delete_sommeil, name='delete_sommeil'),
    path('user/save_token/', save_expo_token, name='save_expo_token'),
    path('temperatures/', add_temperature, name='add_temperature'),
    path('temperatures/baby/<int:baby_id>/', get_temperatures_by_baby, name='get_temperatures_by_baby'),
    path('temperatures/<int:temperature_id>/', update_temperature, name='update_temperature'),
    path('temperatures/<int:temperature_id>/delete/', delete_temperature, name='delete_temperature'),
    path('medicaments/', add_medicament, name='add_medicament'),
    path('medicaments/baby/<int:baby_id>/', get_medicaments_by_baby, name='get_medicaments_by_baby'),
    path('medicaments/<int:medicament_id>/', update_medicament, name='update_medicament'),
    path('medicaments/<int:medicament_id>/delete/', delete_medicament, name='delete_medicament'),
    path('cry_detection/', detect_cry, name='detect_cry'),
    path('delete_baby/<int:baby_id>/', delete_baby, name='delete_baby'),
]
